// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnpdLIfJ2MpkZAjomWHRQ2wz_N0k8MTtM',
    appId: '1:167690796024:web:1c6a7bcaf9450188b1340d',
    messagingSenderId: '167690796024',
    projectId: 'digikhata-clone-bd557',
    authDomain: 'digikhata-clone-bd557.firebaseapp.com',
    storageBucket: 'digikhata-clone-bd557.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0ASx3bdiYWTXuh7e0NZMqwZ_9kjfDHnI',
    appId: '1:167690796024:android:ddea3c45fae0d5c6b1340d',
    messagingSenderId: '167690796024',
    projectId: 'digikhata-clone-bd557',
    storageBucket: 'digikhata-clone-bd557.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAUD9LYZIxgf0ucfoIsST3hY4EsSDKjYw',
    appId: '1:167690796024:ios:8bf005183c41a431b1340d',
    messagingSenderId: '167690796024',
    projectId: 'digikhata-clone-bd557',
    storageBucket: 'digikhata-clone-bd557.firebasestorage.app',
    iosBundleId: 'com.example.digikhataClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAUD9LYZIxgf0ucfoIsST3hY4EsSDKjYw',
    appId: '1:167690796024:ios:8bf005183c41a431b1340d',
    messagingSenderId: '167690796024',
    projectId: 'digikhata-clone-bd557',
    storageBucket: 'digikhata-clone-bd557.firebasestorage.app',
    iosBundleId: 'com.example.digikhataClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnpdLIfJ2MpkZAjomWHRQ2wz_N0k8MTtM',
    appId: '1:167690796024:web:fdaf186bd5193837b1340d',
    messagingSenderId: '167690796024',
    projectId: 'digikhata-clone-bd557',
    authDomain: 'digikhata-clone-bd557.firebaseapp.com',
    storageBucket: 'digikhata-clone-bd557.firebasestorage.app',
  );
}
